name: CD:- Cloudformation

on:
  workflow_call:
  push:
    branches:
      - main

jobs:
  CheckLinting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install serverless dependency
        run: yarn install --frozen-lockfile
      - name: Check Linting
        run: yarn lint
      - name: Check Linting
        run: yarn type-check
  Deploy:
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_REGION: ap-south-1
      SERVICE_NAME: ci-cd-learning
      STAGE: prod
      DEPLOYMENT_BUCKET: ci-cd-learning-deployments-bucket
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install serverless dependency
        run: yarn install --frozen-lockfile
      - name: Package Functions
        run: npx serverless package
      - name: Deploy Functions
        run: npx serverless deploy --package .serverless
